
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  database: <%= ENV['DB_NAME'] %>

production:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: 5432
  database: <%= ENV['DB_NAME'] || 'test_db' %>
  username: <%= ENV['DB_USERNAME'] || 'admin' %>
  password: <%= ENV['DB_PASSWORD'] || 'admin' %>
  timeout: 5000

cable:
  <<: *production