
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default
  host: <%= ENV['DB_TEST_HOST'] || 'localhost' %>
  port: <%= ENV['DB_TEST_PORT'] || 5432 %>
  database: <%= ENV['DB_TEST_NAME'] || 'test_db' %>
  username: <%= ENV['DB_TEST_USERNAME'] || 'admin' %>
  password: <%= ENV['DB_TEST_PASSWORD'] || 'admin' %>
  timeout: 5000