default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ENV['DB_NAME']
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
  host: ENV['DB_HOST']
  port: 5432
  sslmode: require

test:
  <<: *default
  database: web_test
  username: postgres
  password:
  host: localhost

production:
  <<: *default
  database: ENV['DB_NAME']
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
  host: ENV['DB_HOST']
  port: 5432
  sslmode: require